
export type Difficulty = 'easy' | 'medium' | 'hard';

export interface MapConfig {
  id: string;
  title: string;
  description: string;
  areaUrl: string;  // For defining regions/pieces
  depthUrl: string; // For 3D displacement
  colorPalette: string[];
  thumbnail: string;
}

export interface SessionStatus {
  sessionId: string;
  mapId: string;
  difficulty: Difficulty;
  activePlayers: number;
  status: 'available' | 'active' | 'completed';
  startTime: number; // Timestamp
}

// Configuration generated by the server to ensure all clients
// generate the exact same puzzle (same number of pieces, same logic)
export interface SessionConfig {
  randomFactor: number; // 0.5 to 1.5, affects color threshold (piece count)
  scatterSeed: number[]; // Array of random numbers for initial positions
}

export interface Point {
  x: number;
  y: number;
}

export interface VoxelCell extends Point {
  depth: number; // 0-255 value from depth map
  color: string; // Hex color for this specific voxel
}

export interface Region {
  id: string;
  color: string; // Representative color for the group
  originalColor: { r: number; g: number; b: number };
  cells: VoxelCell[]; // Coordinates relative to the grid
  center: Point; // The centroid, used for positioning
  bounds: { minX: number; maxX: number; minY: number; maxY: number };
}

export interface PieceState {
  id: string;
  groupId: string; // Key for grouping pieces together
  // Position is relative to the world origin.
  // When grouped, all pieces in the group maintain their relative offsets.
  position: [number, number, number]; 
  isSolved: boolean; // True if the entire puzzle is complete
  heldBy?: string; 
}

export interface GameState {
  currentView: 'lobby' | 'game';
  selectedMapId: string | null;
  selectedDifficulty: Difficulty;
  activeSession: SessionStatus | null;
  isPreviewingSolved: boolean;
  
  // Persisted Init Data
  sessionConfig: SessionConfig | null;
  pendingServerStates: Record<string, PieceState> | null;

  // Puzzle State
  puzzleRegions: Region[];
  pieceStates: Record<string, PieceState>;
  
  // Interaction State
  hoveredPieceId: string | null;
  draggedPieceId: string | null;
  snapCandidateGroupId: string | null; // The group we might snap to
}

// --- WebSocket Message Types ---

export type ClientMessage = 
  | { type: 'JOIN_SESSION'; mapId: string; difficulty: Difficulty }
  | { type: 'MOVE_PIECE'; pieceId: string; position: [number, number, number] }
  | { type: 'MERGE_GROUP'; sourceGroupId: string; targetGroupId: string; alignOffset: [number, number, number] }
  | { type: 'LEAVE_SESSION' };

export type ServerMessage = 
  | { type: 'SESSION_LIST'; sessions: SessionStatus[] }
  | { type: 'SESSION_JOINED'; session: SessionStatus; config: SessionConfig; currentStates: Record<string, PieceState> }
  | { type: 'PIECE_MOVED'; pieceId: string; position: [number, number, number]; groupId: string }
  | { type: 'GROUP_MERGED'; sourceGroupId: string; targetGroupId: string; alignOffset: [number, number, number] }
  | { type: 'PLAYER_COUNT'; count: number }
  | { type: 'GAME_COMPLETED' };

// Fix for R3F Intrinsic Elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      ambientLight: any;
      pointLight: any;
      directionalLight: any;
      group: any;
      mesh: any;
      boxGeometry: any;
      planeGeometry: any;
      meshStandardMaterial: any;
      meshBasicMaterial: any;
      instancedMesh: any;
      gridHelper: any;
      color: any;
    }
  }
}